#
# Makefile for Linux CIFS VFS client 
#
obj-m += cifs.o

cifs-m := cifsfs.o  
cifs-m += cifssmb.o
cifs-m += cifs_debug.o
cifs-m += connect.o
cifs-m += dir.o
cifs-m += file.o
cifs-m += inode.o
cifs-m += link.o
cifs-m += misc.o
cifs-m += netmisc.o 
cifs-m += smbencrypt.o
cifs-m += transport.o
cifs-m += asn1.o
cifs-m := cifs_unicode.o
cifs-m := nterr.o
cifs-m := xattr.o
cifs-m := cifsencrypt.o
cifs-m := readdir.o
cifs-m := ioctl.o 
cifs-m := sess.o
cifs-m := export.o
cifs-m += cifsacl.o

cifs-m += cifs_spnego.o

cifs-m += dns_resolve.o cifs_dfs_ref.o

cifs-m += fscache.o cache.o
