#
# Makefile for Linux CIFS VFS client 
#
obj-m += cifs.o

obj-m := cifsfs.o  
obj-m += cifssmb.o
obj-m += cifs_debug.o
obj-m += connect.o
obj-m += dir.o
obj-m += file.o
obj-m += inode.o
obj-m += link.o
obj-m += misc.o
obj-m += netmisc.o 
obj-m += smbencrypt.o
obj-m += transport.o
obj-m += asn1.o
obj-m := cifs_unicode.o
obj-m := nterr.o
obj-m := xattr.o
obj-m := cifsencrypt.o
obj-m := readdir.o
obj-m := ioctl.o 
obj-m := sess.o
obj-m := export.o
obj-m += cifsacl.o

obj-m += cifs_spnego.o

obj-m += dns_resolve.o cifs_dfs_ref.o

obj-m += fscache.o cache.o
